spring:
  web:
    resources:
      static-locations: classpath:/public/
  thymeleaf:
    #    关闭缓存
    cache: false
  datasource:
    druid:
      url: jdbc:mysql://43.138.167.39:3306/sm_sql
      username: root
      password: aBOpZvnq9f2FH/FAWIELQEnXlFQFMKryDRbVvLMUwExCcwB1dZpsoP+aQaosEDj0ouUYeTFlKRF69YQxz5/lkQ==
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: config
      #设置密码需要加密，并配置publickey
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALoNT95K2R8a2WBqbnfOTn5st6kSsNq8A8kDmitDWYen24h8G5RltkCTTQlPMOwcpVd4e/zOi5qZzvWy/O9QmDkCAwEAAQ==
      #初始化连接数
      initial-size: 1
      #最大连接数量
      max-active: 20
      #获取连接时最大等待时间
      max-wait: 10000
      #最小连接数量
      min-idle: 1
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #用来检测连接是否有效的SQL，解决数据库断开连接的问题
      validation-query: select 1
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
alipay:
    appid: 9021000123615004
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyzNIfSxqCusjqeUnQH3O+bc1BMIQum/jn48G1TuJbZ6V03xA4SFj9MhkIb7XlE88onV59DjsTfIDY/JyvcL5VsaCfridec47TBNvE24j5S7QdMrjdaegDTtZes/Kh3dUxM7ni92tDnkf5hjVQLvWdyOiyUJvGlyzQDNmH5egZkRNr1NINo82KEl51TqIJdUMbPJ+WqougLMrHcRRAmFlfzKwViiai7heTDXoGJbCG7mnUVu8j2PMYZ+ZseSDJUqsuaJ+sGAudKvoHRbvYGBErIJnKuDkjuyq3BbLZlzPR8hlRC4NA7x5KskEAFCmgwUZdxvDm9s01hHDTO2GqdBv1AgMBAAECggEAfBrAyinGF/FwHZfcTRJXs1jhfBsh1Hw8czBaNu+vHATACnP9/SLyaaRJTdrEJWHvi2BXwnOLO8ZSZMpKM1gNNMvbEpq+Bsgs3Xlk1aoP1AHg3ddkC4NEIG+rSgabJhEktkcSAmD72e5WRPMLtEE0CLX4FjTvOxOZbjtNDg/dX0hy0gSdTrsL9Gvvl5ZA6CZZxSuacrVPFTPnUWIcW/Yo7PHkgobbCJXQSNc/+s8RdEVAQGHUO93H4O+IAXb8pbM1OaAvrwpEiiRr4/I0WZl0kSi80s8g7Sn7HZ5tvv5PMW/dL84IUwSLR/jdl4lpLsiN+1H3TJ9eFIOOByahdwxQoQKBgQDkUm3ie76zC1jOA7lRrWXNKZvy3maguOebYufU56zZUfYCeWAKJampaUJF9kbc1hZvOPbW0G/SRbe6Ldm7NitfEUMYwzRG+TUmmATQ4Thw4kCinHf/CgIi4uCkvCPvkHEF8PiRhCQSrzqWu17rgBQCoQAbvKDPxqswgqKRMGvd/QKBgQDIeZD9c5q++tQJefa9C7eoQizf/JfORyIWcA8u77wR/1wA5kHXHR+7i+p6SkfIXarbw21wx1SlCua76kHf3JLgpFbehWFhqzhii7lIOm+Ca6K68xeoeb/TypGj5RJBM5HR//CXhNweQqTi66eaRmr6EjHaEFZvrTp+1FDjcadbWQKBgQDFhIWpE3ISw/MsLc6I2R+jT6aogTt5ONyr8PErnsxKKHxRAZ1SyegvNW7uxTHiY5Z+22G2zhSebE+X0Yh1S1RT5sQLzPsRlw8i9wnbharlBOXzhrbMPGVCttCt0lCoM2WDRUZT5GOsgkiGE0v3IRKuf4dvd0wK0wxPaAOo5KG8JQKBgDkhC4RukUajTBF3RC0TTb8RPKCH5urNspUaUflaMAog7yMCevjGP+i+Mo+u403iA3Kk+mcNJr3xoVcjpqoYvXJu4qJ++AVRObw7fQ1sOaK88Z6875z/NP8x1tcRzGXwQDnL6dAD+IZXD43rAdQhBRNGZBZ0WW1xvB2we2yVUs/hAoGBAOHwJBkFJRude6QvEc6vXf5G3BOVcK6dYzYGPMiS20StZ+VJ79PD0BISAiBApNJN8qybm4VPybM5EQMxBlxCCYNk1ZNwoc3sJGDVKc8f23RIkZj4kyaJTwITANd7nVY9O30VBS+uKvcGjAKuDZWHfLUa5ZVJDnC9AfJO30aQKEgZ
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzFN9KMZIsN3/F0QiDv9hJP6CtFWlPnvtoxlpRrqoeawxpWEyFtbpk/AHspsupbShb4ttJQ6GUr9iEbXatV5Ktfp+DV99Q/zRv4Pv41IV+b62vd8uf3+rAIALzE/eZWfKoDNf/HD7uFw8tUsR/u0m0HniDHTUkp+w+sagqAjUQoZ7AbB7bJXrDuFwUTJHj92n0T2+Afg34PHtkD6wwcYg6s8Jk4ZhH6WKrmIZnyorq6Znixsh8ZpEvfu489IOumlpyHQsJNbpBSg1K9CNAootHoDhmZ5oKCRRZjl/hQJFiqaorsgw1yrxRV+uW+lnug3xX6++Pe8gjGxT5uVOKYFKVwIDAQAB
    notifyUrl: http://43.138.167.39:8080/alipay/notify
    returnUrl: http://43.138.167.39:8080/index/order
mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  type-aliases-package: com.hp.vo, com.hp.pojo
server:
  port: 8080